spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    database: postgresql
    properties:
      hibernate:
        format_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
