server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://prod-auth-db:5432/authdb
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  rabbitmq:
    host: rabbitmq.prod.svc.cluster.local
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.prod.svc.cluster.local:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
